SELECT * FROM WALMART_DATASET;

-- IMPORTANT KPI'S

SELECT COUNT(DISTINCT STORE) AS NUMBER_OF_STORE ,SUM(WEEKLY_SALES) AS TOTAL_SALES, AVG(WEEKLY_SALES) AS AVERAGE_SALES , AVG(TEMPERATURE) AS AVERAGE_TEMPERATURE, AVG(FUEL_PRICE) AS AVERAGE_FUEL_PRICE, AVG(CPI) AS AVERAGE_CPI, AVG(UNEMPLOYMENT) AS AVG_UNEMPLOYMENT FROM WALMART_DATASET;

-- correlation between CPI AND SALES

SELECT CPI, ROUND(AVG(WEEKLY_SALES),0) AS AVERAGE_SALES FROM WALMART_DATASET GROUP BY CPI ORDER BY CPI;

-- correlation between UNEMPLOYMENT AND SALES

SELECT UNEMPLOYMENT , ROUND(AVG(WEEKLY_SALES),0) AS AVERAGE_SALES FROM WALMART_DATASET GROUP BY UNEMPLOYMENT  ORDER BY UNEMPLOYMENT;

-- SALES PERFORMANCE DURING HOLIDAY
 
SELECT HOLIDAY_FLAG, ROUND(AVG(WEEKLY_SALES),0) AS AVERAGE_SALES FROM WALMART_DATASET GROUP BY HOLIDAY_FLAG ORDER BY HOLIDAY_FLAG;

-- TOP 10 PERFORMING STORES 

SELECT STORE,ROUND(SUM(WEEKLY_SALES),0) AS AVG_SALES FROM WALMART_DATASET GROUP BY STORE ORDER BY SUM(WEEKLY_SALES) DESC LIMIT 10;

-- TOP 10 PERFORMING STORES - AVG-SALES

SELECT STORE,ROUND(AVG(WEEKLY_SALES),0) AS AVG_SALES FROM WALMART_DATASET GROUP BY STORE ORDER BY AVG(WEEKLY_SALES) DESC LIMIT 10;

-- SALES DISTRIBUTION BY TEMPERATURE RATE



WITH CTE AS (
SELECT *,
	CASE
    WHEN TEMPERATURE < 30 THEN "BELOW 30"
    WHEN TEMPERATURE BETWEEN 30  AND 60 THEN "BETWEEN 30-60"
    WHEN TEMPERATURE BETWEEN 60  AND 90 THEN "BETWEEN 60-90"
    ELSE "ABOVE 90"
    END AS TEMP_RANGE
FROM WALMART_DATASET)

SELECT TEMP_RANGE, ROUND(SUM(WEEKLY_SALES),0) AS TOTAL_SALES, ROUND(AVG(WEEKLY_SALES)) AS AVERAGE_SALES FROM CTE GROUP BY TEMP_RANGE;


-- SALES DISTRIBUTION BY FUEL_PRICE

WITH CTE AS (SELECT *,
	CASE 
    WHEN FUEL_PRICE <2 THEN "BELOW 2"
    WHEN FUEL_PRICE BETWEEN 2 AND 3 THEN "2-3"
    WHEN FUEL_PRICE BETWEEN 3 AND 4 THEN "3-4"
    ELSE "ABOVE 4"
    END AS FUEL_RANGE
    FROM WALMART_DATASET)
    
    SELECT FUEL_PRICE, ROUND(SUM(WEEKLY_SALES),0) AS TOTAL_SALES, ROUND(AVG(WEEKLY_SALES)) AS AVERAGE_SALES FROM CTE GROUP BY FUEL_PRICE ORDER BY FUEL_PRICE DESC;
    
    
-- MONTLY VS AVG SALES

SELECT STORE ,YEAR(DATE) AS YEAR, MONTH(DATE) AS MONTH, SUM(WEEKLY_SALES) AS TOTAL_SALES, AVG(WEEKLY_SALES) AS AVERAGE_SALES  FROM WALMART_DATASET GROUP BY STORE,YEAR(DATE),MONTH(DATE);
 
-- SALES OF STORE OVER THE YEARS
 
SELECT STORE,YEAR(DATE) AS YEAR, SUM(WEEKLY_SALES) AS TOTAL_SALES FROM WALMART_DATASET GROUP BY STORE,YEAR(DATE) ORDER BY STORE,SUM(WEEKLY_SALES) DESC ;

-- SALES OF STORE OVER THE MONTHS
 
SELECT STORE,MONTH(DATE) AS MONTH, SUM(WEEKLY_SALES) AS TOTAL_SALES FROM WALMART_DATASET GROUP BY STORE,MONTH(DATE) ORDER BY STORE,SUM(WEEKLY_SALES) DESC ;


-- SALES PERFORMANCE ON WEEKENDS

SELECT *,DAYNAME(DATE) FROM WALMART_DATASET; 



-- 🔍 Findings:

-- - Total Sales: The dashboard reveals a robust total sales figure of $6.74 billion.

-- - Sales Trends: A downward trend in total sales from 2010 to 2012, with monthly fluctuations showing December as the peak sales month.

-- - Top Performing Stores: Store 20 leads with $301.4 million in sales, followed by Store 4 with $299.5 million.

-- - Holiday Impact: The majority of sales occur on regular workdays ($6,231.9 million) compared to holidays ($505.3 million).

-- - External Factors: Temperature, fuel prices, CPI, and unemployment rates all have varying degrees of impact on sales.
